AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: >
  AWS Lambda trigger to process new items in a stream from a DynamoDB table.

Parameters:
  stack:
    Type: String
  runtime:
    Type: String
    Default: 'nodejs12.x'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub ${stack}
      AttributeDefinitions: 
        - AttributeName: Username
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema: 
        - AttributeName: Username
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  DynamoDBStreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${stack}
      CodeUri: code/
      Handler: index.handler
      Runtime: !Sub ${runtime}
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 3 # How many items we want to process at once
            StartingPosition: TRIM_HORIZON
      Policies:
        - AWSLambdaDynamoDBExecutionRole # Managed Policy
