# user

type User {
  id: Int!
  name: String!
}

extend type Query {
  signin(id: Int!): User!
  signout(id: Int!): User!
  friends: [User]!
}

extend type Mutation {
  signup(id: Int!, name: String!): User!
}
